name: NPM Publish
on:
  workflow_call:
    inputs:
      version:
        description: "The version to publish"
        required: true
        type: string
      npm_tag:
        description: "The npm dist-tag to publish under"
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.version }}

      - uses: actions/setup-node@v6
        with:
          node-version: "24.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install pnpm
        uses: pnpm/action-setup@v5

      - name: Install dependencies
        run: pnpm i

      - name: Build
        run: pnpm run build

      - name: Set dynamic package version
        run: npm version ${{ inputs.version }} --no-git-tag-version

      - name: Publish to npm
        run: npm publish --access public --tag ${{ inputs.npm_tag }}